### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by froi**
Hi team.

I'd like to see what all of you think about this. There are parts that will probably not be important for us yet. That said I don't think it hurts to have them there either.

Issue ref: #6

### CODE REVIEW

**Comment by CharlesDLandau** [comment]
May be worth investigating whether Code for America/Code for DC has their own code of conduct template. Merging this would be a good activity for the next meetup.

**Comment by froi** [comment]
I didn't find anything for projects. The code of conduct in the Code for DC website repo is for events. I didn't really find anything for Code for America either. I agree that this is a good thing to solve during the next project night.

**Comment by froi** [comment]
I posted the question into the Code for DC slack and the `DCAF` project used https://www.contributor-covenant.org/, which is the one in this PR.

**Comment by froi** [comment]
Thanks for the input @CharlesDLandau I'll talk to the owners of the org to get you into this repo as well.

**Pull request merged**
