### PR TITLE
Fix page crash

### PR DESCRIPTION
**Pull request by cmazzullo**
Solves #76 #67 
Added missing "Grid" and "CardContent" imports in "CaseRow"
Added test
This depends on Jest (discussion in another issue) so I'd hold off on merging this until that's merged

### CODE REVIEW

**Comment by cmazzullo** [comment]
This includes Jest setup -
Solves #75

**Comment by CharlesDLandau** [comment]
Thanks Chris! I'm hoping to respond all outstanding PRs in the next couple of days.

**Comment by cmazzullo** [comment]
no problem!

**Comment by CharlesDLandau** [comment]
Thanks for the PR!

**Pull request merged**
