### PR TITLE
Rich Text Editor Draft

### PR DESCRIPTION
**Pull request by CyberD123**

### CODE REVIEW

**Comment by CyberD123** [comment]
This is a draft component for a multi-line text field that can serve as a basic form field for the attorney to write their notes. It was based on the existing EvaluatorInfoTable.js component, updates were made to name the component AttyExtraNotes.js and to make the name change throughout the file and the references made to it in CaseTable.js.   The AttyExtraNotes function was updated from the EvaluatorInfoTable function and still has the value storage of evaluatorName that needs to be updated/removed, around line 24 and other places in the file, ex:
const [name, setName] = useState(value.caseData.evaluatorName);

Some other clean up is needed, to finish the transition from being an EvaluatorInfoTable component to an AttyExtraNotes.

**Comment by froi** [comment]
Thanks for the PR @CyberD123! 

Looking forward to see what comes out of it 😄

**Comment by CyberD123** [comment]
screenshot_evaluator_notes_update

**Comment by CyberD123** [comment]
Thanks @froi !!  I've made some updates and attached a screen shot above to show what it looks like.
I'm still learning git, so I'm trying to figure out how to commit to my branch and will ask for help at Tuesday's project night. In the meantime, here are the changes I've made:

changed "Attorney Extra Notes" to "Evaluator Comments" to match existing naming schema & json references
updated evaluatorName to evaluatorComments in file references, etc.
moved Evaluator Comments up in the layout so as to couple with Evaluator Info
updated Textfield id to: id="comments-field"

**Pull request merged**
