### PR TITLE
Rfj 64 reset form

### PR DESCRIPTION
**Pull request by Fran33**
Request to pull from Fran33 RFJ-64-Reset-Form into codefordc rfj master

There are verbose comments in each useEffect function, those may be better put in a documentation or code review tips place.
The various components differ on which have local useState and which have useContext.
But essentially the props plus useEffect allows reset button to pass fresh props to update component state back to template data.
I also removed the precommit stage, I could never get that to work locally.

### CODE REVIEW

**Comment by froi** [comment]
Hey @Fran33 

Sorry to read that you could not make this work locally. Do you mind mentioning in an issue what was the problem? I'd like to make this as smooth as possible for new contributors as we can.

Thanks for the PR. We'll take a look at it soon.

**Comment by blingit** [comment]
Hi @Fran33,

I like the changes addressing issue 64. Most of the fields are being reset, but the date values are persisting after the reset button is pressed. I approve of the changes up to now, but resetting the date fields will still need to be addressed.

**Comment by Fran33** [comment]
@blingit @cmazzullo I updated my branch, per the rewrite of CaseTable. Please review again.
I don't recall what the effect of reverting charges should be. I thought that was already working before I made my branch.

**Comment by cmazzullo** [comment]
Thanks for the push! Should be able to CR this later today

**Comment by cmazzullo** [comment]
There were a couple issues I noticed running this branch locally:
- Adding a new case causes the "Case Info" section (evaluator name, client ID, etc) section to be cleared
- Disposition Date in fresh Cases shows an error ("Invalid Date format")
- The "Reset Form" button doesn't clear charge data, only the "Case Info" section
- I would prefer not to remove linting from the pre-commit step - you can check where the linting issues are (without doing a commit) by running: `npx run lint`

Here is the output of that for the branch, addressing these linting issues will allow you to commit without a problem:
```
/home/chris/projects/rfj_expungement/components/ClientInfoTable.js
  39:12  error  'props' is not defined  no-undef
  40:20  error  'props' is not defined  no-undef
  41:19  error  'props' is not defined  no-undef
  42:13  error  'props' is not defined  no-undef
  43:24  error  'props' is not defined  no-undef
  44:7   error  'props' is not defined  no-undef

/home/chris/projects/rfj_expungement/components/ComposedDatePicker.js
  1:27  error  'useContext' is defined but never used   no-unused-vars
  2:10  error  'CaseContext' is defined but never used  no-unused-vars

/home/chris/projects/rfj_expungement/components/EvaluatorCommentsTable.js
  26:17  error  'props' is not defined  no-undef
  27:7   error  'props' is not defined  no-undef

/home/chris/projects/rfj_expungement/components/EvaluatorInfoTable.js
  29:13  error  'props' is not defined  no-undef
  30:7   error  'props' is not defined  no-undef

✖ 12 problems (12 errors, 0 warnings)
```

**Comment by Fran33** [comment]
@cmazzullo thanks for the review. I fixed all four sets of things you mentioned, and also updated the header to show the evaluator name when entered.

**Comment by cmazzullo** [comment]
Looks good! Merged

**Pull request merged**
